version: "2"
services:

  db:
    image: mysql
    volumes:
      - /etc/my.cnf:/etc/my.cnf
      - /data/docker/test/test2/db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD: 123456
  blog:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - /data/www/GitHub/blog_project:/data/www/GitHub/blog_project
    ports:
      - "50090:80"
    links:
      - db
    environment:
      - DEBUG=true

